<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3307/airlabsdb_thuc?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
=======
spring.datasource.url=jdbc:postgresql://dpg-d5nel4smrvns73fmrh2g-a.oregon-postgres.render.com:5432/airlabsdb
spring.datasource.username=root
spring.datasource.password=0YtGGV2K2o4SNILlUsBBIIdUS6G24q3F

# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}



>>>>>>> b9dffad58d3c860fe17a1b805fe2b8e94207c4b9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

<<<<<<< HEAD
api-key-airlabs=c0d9c2ac-7c1d-4d1c-ad8b-8dd3473bee3c
=======
api-key-airlabs=3dabb7ef-783d-4518-adc5-9285f232ba17
# api-key-airlabs=${AIRLABS_KEY}
>>>>>>> b9dffad58d3c860fe17a1b805fe2b8e94207c4b9
